### ISSUE TITLE
How to use for STM32F030F4

### ISSUE THREAD

**Issue by AlirezaAbdiyan** [hubmartin/WS2812B_STM32L083CZ#1]
Hi,
I want to use your library for STM32F030F4, I change it a bit but not work for me!
I change TIM2 to TIM3 because STM32F030F4 has not TIM2!
And change this line:
GPIO_InitStruct.Alternate = GPIO_AF2_TIM1;
to
GPIO_InitStruct.Alternate = GPIO_AF0_TIM3; 
Is this ok?!
Thanks.

Regards
AliReza

**Comment by hubmartin** [comment]
You need to change code in the DMA init and IRQ handlers. You have to change DMA stream/channels based on the timer you choosed. Take a look at the DMA peripheral stream/channel matrix and edit the code.

**Comment by AlirezaAbdiyan** [comment]
ok,
Thanks.
